### ISSUE TITLE
Pre-commit errors

### ISSUE THREAD

**Issue by Azaya89** [bokeh/tutorial#22]
I'm trying to make a commit while working on #20 but I'm getting an error during the pre-commit hooks:

```
nbqa-flake8..............................................................Failed
- hook id: nbqa-flake8
- exit code: 1

Traceback (most recent call last):
  File "/Users/mac/.cache/pre-commit/repon0oycc6g/py_env-python3.12/bin/nbqa", line 5, in <module>
    from nbqa.__main__ import main
  File "/Users/mac/.cache/pre-commit/repon0oycc6g/py_env-python3.12/lib/python3.12/site-packages/nbqa/__main__.py", line 28, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

I checked the nbQa repo  here https://github.com/nbQA-dev/nbQA/blob/main/nbqa/__main__.py#L37 and it appears `pkg_resources` has been deprecated. I'm not sure how to proceed with the commits if so...

@bryevdv @tcmetzger

**Comment by pavithraes** [comment]
@Azaya89 - Haven't looked closely, but I see you're using python 3.12 -- several libraries don't fully support this version yet, so I'd suggest trying with 3.11 to unblock sooner. We can also consider capping the python version in our environment file till we can test with 3.12?

**Comment by Azaya89** [comment]
> @Azaya89 - Haven't looked closely, but I see you're using python 3.12 -- several libraries don't fully support this version yet, so I'd suggest trying with 3.11 to unblock sooner. We can also consider capping the python version in our environment file till we can test with 3.12?

Yes, yes. I also tried downgrading the python version to 3.11 but it said some of the dependencies require 3.12:

```
conda install python=3.11
Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pyproj-3.6.1-py312h33684bb_4 requires python >=3.12,<3.13.0a0 *_cpython, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ geopandas is installable with the potential options
│  ├─ geopandas [0.14.1|0.4.1|0.6.1|0.8.1|0.9.0] would require
│  │  ├─ fiona [ |>=1.8.21 ] with the potential options
│  │  │  ├─ fiona 1.9.1 would require
│  │  │  │  └─ libgdal >=3.6.2,<3.7.0a0 , which requires
│  │  │  │     └─ proj >=7.2.0,<7.2.1.0a0 , which can be installed;
│  │  │  ├─ fiona 1.9.5 would require
│  │  │  │  └─ python >=3.12,<3.13.0a0 *_cpython, which can be installed;
│  │  │  ├─ fiona [1.8.13.post1|1.8.22|1.9.1] would require
│  │  │  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │  │  ├─ fiona [1.8.13.post1|1.8.22|1.9.1] would require
│  │  │  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  │  │  └─ fiona [1.8.22|1.9.1] would require
│  │  │     └─ python >=3.10,<3.11.0a0 , which can be installed;
│  │  ├─ geopandas-base [0.14.1 pyha770c72_0|0.9.0 py_1], which requires
│  │  │  └─ pyproj [>=2.2.0 |>=3.3.0 ] with the potential options
│  │  │     ├─ pyproj 3.4.1 would require
│  │  │     │  └─ proj >=8.2.1,<8.2.2.0a0 , which conflicts with any installable versions previously reported;
│  │  │     ├─ pyproj 3.6.1 would require
│  │  │     │  └─ python >=3.12,<3.13.0a0 *_cpython, which can be installed;
│  │  │     ├─ pyproj [3.1.0|3.3.0|3.4.1] would require
│  │  │     │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  │  │     ├─ pyproj [3.1.0|3.3.0|3.4.1] would require
│  │  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │  │     └─ pyproj [3.1.0|3.3.0|3.4.1] would require
│  │  │        └─ python >=3.9,<3.10.0a0 , which can be installed;
│  │  └─ pyproj [ |>=2.2.0 ] with the potential options
│  │     ├─ pyproj 3.4.1, which cannot be installed (as previously explained);
│  │     ├─ pyproj 3.6.1, which can be installed (as previously explained);
│  │     ├─ pyproj [3.1.0|3.3.0|3.4.1], which can be installed (as previously explained);
│  │     ├─ pyproj [3.1.0|3.3.0|3.4.1], which can be installed (as previously explained);
│  │     └─ pyproj [3.1.0|3.3.0|3.4.1], which can be installed (as previously explained);
│  ├─ geopandas 0.12.2 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ geopandas 0.12.2 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ python 3.11**  is not installable because it conflicts with any installable versions previously reported
```

**Comment by ianthomas23** [comment]
@Azaya89 Rather than trying to downgrade the python version of an existing conda environment, it would be better to create a new environment from scratch with the required python version.

**Comment by tcmetzger** [comment]
We have already removed the black pre-commit hook a while back - I'm Ok with removing pre-commit altogether from this repo (including the GH action) since there isn't really that much code anyways and I don't want this to hold up any changes to the notebooks. We can look into re-instating pre-commit at some point in the future!

**Comment by Azaya89** [comment]
I have uninstalled the pre-commits.
